<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0" 
                xmlns:html="http://www.w3.org/1999/xhtml"
                xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"
                xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
  
  <xsl:template match="/">
    <html xmlns="http://www.w3.org/1999/xhtml">
      <head>
        <title>XML Sitemap - Developer Utilities Tool</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <style type="text/css">
          body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
            color: #333;
            background: #f5f5f5;
            margin: 0;
            padding: 20px;
          }
          
          h1 {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 20px;
            margin: -20px -20px 20px -20px;
            border-radius: 8px 8px 0 0;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
          }
          
          .intro {
            background: white;
            padding: 20px;
            margin-bottom: 20px;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
          }
          
          table {
            width: 100%;
            border-collapse: collapse;
            background: white;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
            border-radius: 8px;
            overflow: hidden;
          }
          
          th {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            text-align: left;
            padding: 12px;
            font-weight: 600;
          }
          
          td {
            padding: 12px;
            border-bottom: 1px solid #eee;
          }
          
          tr:hover {
            background: #f8f9fa;
          }
          
          a {
            color: #667eea;
            text-decoration: none;
          }
          
          a:hover {
            text-decoration: underline;
          }
          
          .priority {
            font-weight: 600;
            color: #667eea;
          }
          
          .changefreq {
            text-transform: capitalize;
          }
          
          .footer {
            text-align: center;
            margin-top: 20px;
            padding: 20px;
            color: #666;
            font-size: 14px;
          }
          
          .footer a {
            color: #667eea;
          }
        </style>
      </head>
      <body>
        <h1>🗺️ XML Sitemap</h1>
        
        <div class="intro">
          <p>This is an XML Sitemap, used to help search engines discover pages on this site.</p>
          <p>Number of URLs: <strong><xsl:value-of select="count(sitemap:urlset/sitemap:url)"/></strong></p>
        </div>
        
        <table>
          <tr>
            <th>URL</th>
            <th>Last Modified</th>
            <th>Change Frequency</th>
            <th>Priority</th>
          </tr>
          <xsl:for-each select="sitemap:urlset/sitemap:url">
            <tr>
              <td>
                <xsl:variable name="itemURL">
                  <xsl:value-of select="sitemap:loc"/>
                </xsl:variable>
                <a href="{$itemURL}">
                  <xsl:value-of select="sitemap:loc"/>
                </a>
              </td>
              <td>
                <xsl:value-of select="sitemap:lastmod"/>
              </td>
              <td class="changefreq">
                <xsl:value-of select="sitemap:changefreq"/>
              </td>
              <td class="priority">
                <xsl:value-of select="sitemap:priority"/>
              </td>
            </tr>
          </xsl:for-each>
        </table>
        
        <div class="footer">
          <p>Generated by <a href="https://devutil.dps.codes/">Developer Utilities Tool</a></p>
          <p>View <a href="/sitemap.html">HTML Sitemap</a> for a more visual representation</p>
        </div>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>

